trainingPhrases:
- lookup train times
- when is the next train arriving
- when are the next trains
- when is the next train coming
- when are the next trains arriving
- what are the next arrival times
- when are the next train times
- when is my next train arriving
- when does the next train arrive
- when is the next train
- when will the next train arrive
- what is the next train
- when is the next arrival
- the next train times
- train times
- arrival times
- next trains
- upcoming trains
- upcoming arrivals
- upcoming departures
- next departures
- next arrivals
- times
